# Generated by Django 4.2.7 on 2023-12-08 09:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('quiz_type', models.CharField(choices=[('radio', 'Radio'), ('checkbox', 'Checkbox'), ('input', 'Input')], max_length=20)),
                ('option', models.JSONField(blank=True, null=True)),
                ('answer', models.JSONField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.lesson')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
