# Generated by Django 4.2.7 on 2024-06-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_alter_section_content_alter_section_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
