# Generated by Django 4.2.7 on 2023-12-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_alter_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='quiz_schema',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
