# Generated by Django 4.2.7 on 2024-06-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_alter_content_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='studio.course'),
        ),
    ]
