# Generated by Django 4.2.7 on 2023-12-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_courseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='marks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
