# Generated by Django 4.2.7 on 2024-06-09 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_alter_section_content_alter_section_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certification_course_url',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='is_certification_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
