# Generated by Django 4.2.7 on 2024-06-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_course_certification_course_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={},
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='answer',
            new_name='quiz_schema',
        ),
        migrations.RemoveField(
            model_name='content',
            name='order',
        ),
        migrations.RemoveField(
            model_name='enrollcourse',
            name='is_CourseStarted',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.RemoveField(
            model_name='section',
            name='order',
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
