# Generated by Django 4.2.7 on 2023-12-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_course_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_completed',
        ),
    ]
