# Generated by Django 4.2.7 on 2024-06-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_remove_content_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
