# Generated by Django 4.2.7 on 2024-06-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_quiz_is_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='object_id',
            field=models.UUIDField(null=True),
        ),
    ]
