# Generated by Django 4.2.7 on 2023-12-14 12:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_course_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_completed',
        ),
        migrations.CreateModel(
            name='EnrollCourse',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enrolled', models.BooleanField(blank=True, default=False)),
                ('is_CourseStarted', models.BooleanField(blank=True, default=False)),
                ('is_CourseCompleted', models.BooleanField(blank=True, default=False)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.course')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.profile')),
            ],
            options={
                'unique_together': {('profile', 'course_id')},
            },
        ),
    ]
