# Generated by Django 4.2.7 on 2023-12-15 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_remove_course_is_completed_enrollcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='article_completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_marks',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_result',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='course_progress',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
