# Generated by Django 4.2.7 on 2024-06-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0013_videoprogress_quizprogress_articleprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
