# Generated by Django 4.2.7 on 2023-12-18 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0013_lessoncompletion_delete_courseprogress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessoncompletion',
            unique_together={('profile', 'lesson')},
        ),
    ]
