# Generated by Django 4.2.7 on 2024-06-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0014_alter_section_options_section_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
