# Generated by Django 4.2.7 on 2023-12-21 09:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0014_alter_lessoncompletion_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('thumbnail', models.FileField(default='images/jobs_thumbnail.jpg', upload_to='images/')),
                ('Location', models.CharField(max_length=255)),
                ('Service_type', models.CharField(max_length=255)),
                ('Industry', models.CharField(max_length=255)),
                ('Experience', models.CharField(max_length=255)),
                ('Required_skills', models.CharField(max_length=255)),
                ('Compensation', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
