# Generated by Django 4.2.7 on 2023-12-21 11:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0015_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='profile',
        ),
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.jobs')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
