# Generated by Django 4.2.7 on 2024-06-17 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0016_alter_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollcourse',
            name='course_progress',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
