# Generated by Django 4.2.7 on 2023-12-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0016_remove_jobs_profile_appliedjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
