# Generated by Django 4.2.7 on 2023-12-27 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0017_appliedjobs_is_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrollment_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_courseStarted',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_enrolled',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_signature',
            field=models.FileField(blank=True, default='images/signature.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='enrollcourse',
            name='course_completion_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
