# Generated by Django 4.2.7 on 2024-06-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0017_alter_enrollcourse_course_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='section',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AlterUniqueTogether(
            name='lessoncompletion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lessoncompletion',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lessoncompletion',
            name='profile',
        ),
        migrations.DeleteModel(
            name='AppliedJobs',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='LessonCompletion',
        ),
    ]
