# Generated by Django 4.2.7 on 2023-12-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0018_remove_course_enrollment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollcourse',
            name='course_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
