# Generated by Django 4.2.7 on 2023-12-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0020_lessoncompletion_article_bookmarked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollcourse',
            name='completed_chapter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollcourse',
            name='total_chapter',
            field=models.IntegerField(default=0),
        ),
    ]
