# Generated by Django 4.2.7 on 2023-12-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0022_alter_lessoncompletion_article_bookmarked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollcourse',
            name='completed_chapter',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollcourse',
            name='total_chapter',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
