# Generated by Django 4.2.7 on 2024-01-02 10:50

from django.db import migrations, models
import studio.models.lesson


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0023_alter_enrollcourse_completed_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='article_url',
            field=models.FileField(blank=True, upload_to='media/', validators=[studio.models.lesson.validate_pdf_extension]),
        ),
    ]
