# Generated by Django 4.2.7 on 2024-01-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0025_alter_lesson_article_name_alter_lesson_article_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='quiz_schema',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
