# Generated by Django 4.2.7 on 2024-01-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0026_alter_lesson_quiz_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
